### ISSUE TITLE
Making the json settings file read-only causes apps to crash

### ISSUE THREAD

**Issue by RinTohsaka64** [mysteryx93/HanumanInstituteApps#13]
Hi, I love the apps you built! However, I noticed that if I make the json preferences file read-only, the apps crash when I try to run them.

So I wanted to make the configuration file read-only so that I could start the app normally, select the settings I need, and then set custom default settings by making the configuration file read-only. That way, I don't have to worry about forgetting to revert back, since the other settings are temporary and always revert back to the custom defaults.

I am using Windows 10.

LOL I forgot to say which apps the crashes occur in! But after further testing, the crashes seem to be happening in all four apps.

**Comment by mysteryx93** [comment]
All apps share the same architecture.

I don't know whether setting the file read-only is the right solution for this.

Either way, I guess it wouldn't hurt to not crash the app on failure to save.

OK I made the change. I was just about to publish an update.
