### ISSUE TITLE
Feature Request: 528hz encoding

### ISSUE THREAD

**Issue by lexterror** [mysteryx93/HanumanInstituteApps#20]
Hi,

I like the idea of having 528hz instead of 432hz. Could you please add it? Thank you!

Also, I wrote this small web app: (I thought you might be interested) I hope its not too "off-topic"

https://zen-wood-chime-generator.sourceforge.io/index.html

**Comment by mysteryx93** [comment]
Under settings, you can set it to 528Hz already
