### ISSUE TITLE
432Hz Batch Converter - "Shift pitch" text fields max out at 4 digits (technically 5 if you include a value of 10000)

### ISSUE THREAD

**Issue by NintendoManiac64** [mysteryx93/HanumanInstituteApps#24]
As you know, interpolation and high frame rates can be quite useful, and it's best to use exact multiples e.g. 2x, 3x, etc.

However, many TVs, such as my own, does not support any refresh rates below 49.091Hz nor any refresh rates above 64Hz.

So for 24fps content, I will sometimes instead slightly speed them up to 24.55fps so that, with 2x interpolation, they'll play at 49.1fps.

This is easy enough with true 24.000fps content since the ratio necessary only needs 3 digits for exact precision—with "round pitch" unchecked and "skip tempo adjustment for quality" checked, you simply just set it to shift pitch from 480Hz to 491Hz.

The problem are those pesky 24000/1001 videos (more commonly referred to as 23.976) since the exact ratio for that would be shifting pitch from 480000Hz to 491491Hz which requires 6 digits of precision, and 432Hz Batch Converter only allows for 4 digits of precision (technically 5 if you include a value of 10000Hz).

**Comment by mysteryx93** [comment]
What's the actual problem, and what would you suggest as a solution?

**Comment by NintendoManiac64** [comment]
> the exact ratio for that would be shifting pitch from 480000Hz to 491491Hz which requires 6 digits of precision, and 432Hz Batch Converter only allows for 4 digits of precision

I'm just looking for more than 4 digits of precision is all.

**Comment by mysteryx93** [comment]
It might be a display-only limitation. I could allow displaying more digits. I suspect it's parsing your 9 digits anyway.

**Comment by NintendoManiac64** [comment]
I just did some tests and I can definitely say that it's not just a visual issue and it is in fact limited to 4 digits of precision.

I simply generated a sine wave in Audacity with a length of 491491 samples which, in the aforementioned scenario, should have the resulting sped-up audio have a length of 480000 samples... but it does not.

By contrast, if I generate a sine wave in Audacity with a length of 491400 samples, then the aforementioned scenario *does* indeed give the resulting sped-up audio a length of exactly 480000 samples due to the fact that 491491 was truncated to 4914.

**Comment by mysteryx93** [comment]
I looked at the Shift Pitch box, it allows any digits of precision you need.

Do you need to put a value above 10000Hz?? What for? That would just result in a super high-pitch noise.

**Comment by NintendoManiac64** [comment]
> That would just result in a super high-pitch noise.

That's only if you have auto pitch-detection enabled.

The issue is that I have that function unchecked and so I'm specifying both the input and the output pitch, and I'm putting in a source value that is *definitely* higher than the actual pitch in order to have greater precision.

For example, the automatic pitch detection can detect values like 441.4 so, in order to manually recreate that, I have to put in a source value of 4414 (without decimal) and an output pitch of 4320. But that's all the more I can do—I can't put in even more precision, like from 441325 to 432000 where 441325 represents a pitch of 441.325Hz.

**Comment by mysteryx93** [comment]
If it's only the ration between the 2 values that matter, why can't you put decimals in both values?

**Comment by NintendoManiac64** [comment]
...holy bananas, I had no idea it accepted up to 14 decimal places!

In the past, gosh, uh... decade?  In order to test how many digits a text field accepts in a program or a website, I always just first type `12345678901234567890...` and, when I did that, it truncated the result to only 4 digits.

It never even crossed my mind that it'd truncate digits differently if you used a decimal point!

I guess my problem is solved then, but Isn't this sort of inconsistent behavior in the UI?

**Comment by mysteryx93** [comment]
Values that are too far out could cause problems, no guarantee that they'd play properly, and it's not the intended purpose. As for decimals, I have no reason for rounding. Higher precision can end up useful sometimes.

So I'll close this.
