### ISSUE TITLE
Question - does purchasing a license provide any perks other than ad free?

### ISSUE THREAD

**Issue by NintendoManiac64** [mysteryx93/HanumanInstituteApps#30]
I'm just wondering if purchasing a license provides anything more than the "warm fuzzies" of knowing that you're helping the projects development, i.e. if it also gives you access to priority support or the like.

**Comment by mysteryx93** [comment]
I do give more support to those with a license, but really haven't been able to put any more time into this. I'll rethink the whole license thing when I'm ready to put more development into this.

**Comment by NintendoManiac64** [comment]
With that in mind, I'll open an "enhancement" issue for 128gain／replaygain／wavegain mainly just to have things consolidated in one place as something I mentioned off-hand previously but understanding that nothing will come of it at this time even if I were to purchase a license.

**Comment by NintendoManiac64** [comment]
> I do give more support to those with a license

I did just purchase a license, but I'm uncertain how to prove this—do you get notification or something of the keys purchased by others? My license key was (with the middle parts censored):
4A___15-95__D6-D5__F5-76___C5

**Comment by mysteryx93** [comment]
Yes I get notifications of orders.

Finances are in a tough spot and I got lots of other priorities, must get my business back on track as a priority.

[Avalonia 11.1](https://github.com/AvaloniaUI/Avalonia/releases/tag/11.1.0-beta2) should be released soon; I'll probably release a new version after that's released.
